# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [ ]:
print("list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；\n"
      "tolist() 才能達成多層的型態轉換。"
      )

'\nYour Code\n'

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(10, size=6) 
print(a)
print(a.ndim) #陣列維度
print(a.shape) #維度形狀
print(a.size) #維度數木
print(a.dtype) #資料型態
print(a.itemsize)#記憶體大小
print(len(a)) #最高維度
print(type(a)) #資料型態

[1 1 2 0 1 6]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [ ]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print(b.ndim) #陣列維度
print(b.shape) #維度形狀
print(b.size) #維度數木
print(b.dtype) #資料型態
print(b.itemsize)#記憶體大小
print(len(b)) #最高維度
print(type(b)) #資料型態

[[0 7 9 3]
 [8 2 7 7]
 [9 3 3 3]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [2]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(c.ndim) #陣列維度
print(c.shape) #維度形狀
print(c.size) #維度數木
print(c.dtype) #資料型態
print(c.itemsize)#記憶體大小
print(len(c)) #最高維度
print(type(c)) #資料型態

NameError: name 'np' is not defined

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [ ]:
def tolist(arry):
    print(arry.tolist())

[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]


In [ ]:
print(tolist(a))

[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]


In [ ]:
print(tolist(b))

In [ ]:
print(tolist(c))