# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [6]:
import numpy as np

a=np.arange(1,7)
print(a)

print(a.sum())
print(np.sum(a))
print(sum(a))

# 一模一樣

[1 2 3 4 5 6]
21
21
21


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [7]:
# 記得先 Import 正確的套件
import numpy as np

In [8]:
A = np.random.random((5, 5))

A=(A-A.min())/(A.max()-A.min())
A

array([[0.07955839, 1.        , 0.79499205, 0.2357209 , 0.5755376 ],
       [0.1989924 , 0.66962263, 0.        , 0.77324591, 0.86513231],
       [0.5491708 , 0.34851332, 0.77968305, 0.42121758, 0.14675671],
       [0.0696314 , 0.53089109, 0.87772542, 0.31359346, 0.10632702],
       [0.79339172, 0.44418762, 0.53394023, 0.42458762, 0.97298239]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [9]:
c=np.random.random((10))
c=np.random.randint(1,100,10)

In [10]:
c[np.argmax(c)]=-1
print(c)

[87 32 84 -1 34 51 81 16 41 53]
