# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


zero 一個是0
empty 一個是空值,因為不會初始化，所以內容不確定
empty比較快 zero比較方便

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [1]:
import numpy as np

In [2]:
a= np.random.rand(2,3)
print(a)
print(a//1)
print(np.around(a))
print(a.astype(int))

[[0.95156379 0.13718395 0.61725883]
 [0.38730076 0.52425085 0.51266865]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 1.]
 [0. 1. 1.]]
[[0 0 0]
 [0 0 0]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [3]:
m = 20
n = 40

m=20
n=40
a=np.random.randint(m,n,size=(2,3))
print(a)

[[21 32 38]
 [25 27 26]]
